services:
  api:
    image: node:22-bookworm
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DATABASE: splitflow      
      PASSWORD_PEPPER: 5aa77c91ee8e7dbdf2c4d3140b1921df
      NODE_ENV: dev
      SESSION_SECRET: VWqJxi@HSk3*Yi5U*z319XkSdCFmrul6T@$jDRgO
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: splitflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d splitflow"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
